# Generated by Django 5.1.4 on 2025-03-22 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_settings", "0005_rename_openapi_url_tool_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MCPConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sse_url",
                    models.URLField(
                        help_text="The URL of the SSE endpoint of the MCP server"
                    ),
                ),
                (
                    "sse_token",
                    models.CharField(
                        blank=True,
                        help_text="The token for the SSE endpoint",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "agent_setting",
                    models.ForeignKey(
                        help_text="The agent setting this MCP config belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mcp_configs",
                        to="agent_settings.agentsetting",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.AddIndex(
            model_name="mcpconfig",
            index=models.Index(
                fields=["agent_setting"], name="agent_setti_agent_s_0f0045_idx"
            ),
        ),
    ]
