# Generated by Django 5.1.4 on 2025-05-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_settings", "0006_mcpconfig_delete_tool_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mcpconfig",
            name="sse_headers",
            field=models.JSONField(
                default=dict, help_text="The headers for the SSE endpoint"
            ),
        ),
    ]
