# Generated by Django 5.1.4 on 2025-05-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("agent_settings", "0007_mcpconfig_sse_headers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mcpconfig",
            name="sse_headers",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="The headers for the SSE endpoint",
                null=True,
            ),
        ),
    ]
