services:
  db:
    container_name: hebo-db
    image: postgres:17.4
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hebo
    volumes:
      - ./local-db:/var/lib/postgresql/data