/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "HeboCloudApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "HeboDatabase": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Aurora"
      "username": string
    }
    "HeboDbPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeboDbUsername": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "HeboVpc": {
      "bastion": string
      "type": "sst.aws.Vpc"
    }
    "PosthogHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PosthogKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StackProjectId": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StackPublishableClientKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "StackSecretServerKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}