/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "HeboApi": {
      "service": string
      "type": "sst.aws.Service"
    }
    "HeboCloudApp": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "HeboDatabase": {
      "SQLiteConnectionString": string
      "type": "sst.sst.Linkable"
    }
    "HeboVpc": {
      "type": "sst.aws.Vpc"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}