# Generated by Django 5.1.4 on 2025-05-22 06:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("knowledge", "0005_page_unique_page_position_per_version_and_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": ["title", "-updated_at"],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
    ]
