# Generated by Django 5.1.4 on 2025-05-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hebo_organizations", "0002_organizationinvitation_is_admin"),
        ("knowledge", "0006_alter_page_options"),
        ("versions", "0003_versionslug_unique_version_slug_per_organization"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_page_position_per_version_and_parent",
        ),
        migrations.RemoveField(
            model_name="page",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="page",
            name="position",
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                fields=("version", "title"), name="unique_page_title_per_version"
            ),
        ),
    ]
