# Generated by Django 5.1.4 on 2025-05-22 08:28

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hebo_organizations", "0002_organizationinvitation_is_admin"),
        (
            "knowledge",
            "0007_remove_page_unique_page_position_per_version_and_parent_and_more",
        ),
        ("versions", "0003_versionslug_unique_version_slug_per_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("title"),
                    "-updated_at",
                ],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        migrations.RemoveConstraint(
            model_name="page",
            name="unique_page_title_per_version",
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title__iexact", models.F("title"))),
                fields=("version",),
                name="unique_page_title_per_version",
            ),
        ),
    ]
