# Generated by Django 5.1.4 on 2025-05-22 08:44

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hebo_organizations", "0002_organizationinvitation_is_admin"),
        (
            "knowledge",
            "0007_remove_page_unique_page_position_per_version_and_parent_and_more",
        ),
        ("versions", "0003_versionslug_unique_version_slug_per_organization"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={
                "ordering": [
                    django.db.models.functions.text.Lower("title"),
                    "-updated_at",
                ],
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
            },
        ),
        # Remove constraint if it exists
        migrations.RunSQL(
            sql="""
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM pg_constraint
                    WHERE conname = 'unique_page_title_per_version'
                    AND conrelid = 'knowledge_page'::regclass
                ) THEN
                    ALTER TABLE knowledge_page DROP CONSTRAINT unique_page_title_per_version;
                END IF;
            END $$;
            """,
            reverse_sql="",  # No reverse SQL needed as we're just cleaning up
        ),
        migrations.AddConstraint(
            model_name="page",
            constraint=models.UniqueConstraint(
                condition=models.Q(("title__iexact", models.F("title"))),
                fields=("title", "version"),
                name="unique_page_title_per_version",
            ),
        ),
    ]
