name: Deploy Web App

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
      - 'packages/auth/**'
      - 'infra/stacks/web-stack.ts'
  workflow_dispatch:

jobs:
  deploy-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stage: [staging, prod]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build web app
        run: pnpm turbo build --filter=web...
      - name: Deploy to AWS
        run: pnpm --filter infra deploy --stage ${{ matrix.stage }} --stack web
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DOMAIN_NAME: ${{ secrets.DOMAIN_NAME }}
          HOSTED_ZONE: ${{ secrets.HOSTED_ZONE }}
          NEXT_PUBLIC_POSTHOG_KEY: ${{ secrets.NEXT_PUBLIC_POSTHOG_KEY }}
          NEXT_PUBLIC_POSTHOG_HOST: ${{ secrets.NEXT_PUBLIC_POSTHOG_HOST }} 